Sprint1
Nereee/E4_ML_T7 pull request #1
Opened 2024-04-19 06:16 UTC by Paula-Elorrieta

XML-an printzipioz datu guztiak daude idatzita, baina jarri dugu komentarioak zatiak banatzeko.

2024-04-19 08:01 UTC, Nereee commented
Nabegazio menuak euskaraz egon beharko luke... eta agian ja planifikatu dezakezu zein izango den web gunearen nabegazio menua!!

2024-04-19 08:01 UTC, Nereee requested changes
Nabegazio menuak euskaraz egon beharko luke... eta agian ja planifikatu dezakezu zein izango den web gunearen nabegazio menua!!

2024-04-19 08:04 UTC, Nereee commented
XML FItxategian erreztuko dizue lana eliminatzen baduzue **bajaData**, bestela filtratu beharko dituzue bajaData ez duten langileak... sinplifikatu!

2024-04-19 10:11 UTC, Paula-Elorrieta commented
Aldatu dut XML eta "bajaData" kendu dut, asteburuan beste orri batzuk egingo ditut nabegazio menua betetzeko pizka bat.

2024-04-21 15:02 UTC, Nereee approved these changes

2024-04-21 15:03 UTC, Nereee commented
Oso ondo! Izugarrizko lana. 
Proposamen bat da, ez da beharrezkoa, baina artistak eta albumak txukunago geratuko zen display: grid moduan. Askoz ere moldagarriagoa da horrelako matrize edo parrila bat erakusteko. Ikusiko dugu nola aldatu eta baliogarria egingo zaizue langileen datuak erakusteko!

2024-04-21 15:03 UTC, merged